import React from 'react';

import Head from 'next/head';
import type { NextPage } from 'next/types';

const Blog: NextPage = () => {
	return (
		<>
			<Head>
				<title>Blog 📑 | Vlatko Stojkoski</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='px-5 pt-20 min-h-screen'>
				<h1 className='text-5xl font-bold'>Blog posts</h1>
				<div style={{
					display: 'grid',
					gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
					gridGap: '16px',
				}}>
					lol
				</div>
			</main>
		</>
	);
};

export default Blog;