import React from 'react';

import { type NextPage } from 'next';
import Head from 'next/head';

import ContactSection from 'components/ContactSection';
import CreepyImage from 'components/CreepyImage';
import Footer from 'components/Footer';
import HomeSection from 'components/HomeSection';
import Navbar from 'components/Navbar';
import Pointer from 'components/Pointer';
import PortfolioSection from 'components/PortfolioSection';
import { trpc } from 'utils/trpc';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Vlatko Stojkoski</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar />

			<CreepyImage />

			<Pointer />

			<main className='px-5'>
				<HomeSection />

				<PortfolioSection />

				<ContactSection />
			</main>

			<Footer />
		</>
	);
};

export default Home;
